#!/usr/bin/env python3
"""
Script to create a JSON file with duplicates for testing deduplication.

This script reads the original mocked_response.json and creates a larger file
with intentional duplicates for testing purposes.
- Total records: ~10,000
- ~5,000 unique records (generated by modifying original data)
- ~5,000 duplicate records (copies of the unique ones)
"""

import json
import random
import copy
from pathlib import Path
from datetime import datetime, timedelta
import sys


def load_original_data(file_path: Path) -> dict:
    """Load the original JSON data."""
    print(f"Loading original data from {file_path}...")
    
    if not file_path.exists():
        print(f"Error: Original file {file_path} not found!")
        sys.exit(1)
    
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    original_records = data.get('value', [])
    print(f"✓ Loaded {len(original_records)} original records")
    return data


def generate_variations(base_record: dict, variations_count: int) -> list:
    """Generate variations of a base record to create unique records."""
    variations = []
    
    for i in range(variations_count):
        # Create a copy of the base record
        variation = copy.deepcopy(base_record)
        
        # Modify key fields to make it unique
        variation['field_code'] = random.randint(1, 1000)
        variation['_field_name'] = f"Field_number_{variation['field_code']}"
        variation['well_code'] = random.randint(100, 9999)
        variation['_well_reference'] = f"{random.randint(1,9)}-{chr(random.randint(65,90))}-{random.randint(1,9)}-BA"
        variation['well_name'] = variation['_well_reference']
        
        # Vary production period (random date between 1947 and 2023)
        start_date = datetime(1947, 1, 1)
        end_date = datetime(2023, 12, 31)
        random_date = start_date + timedelta(
            days=random.randint(0, (end_date - start_date).days)
        )
        variation['production_period'] = random_date.strftime("%Y-%m-01T00:00:00+00:00")
        
        # Vary production values
        variation['days_on_production'] = random.randint(1, 31)
        variation['oil_production_kbd'] = round(random.uniform(0, 10), 8)
        variation['gas_production_mmcfd'] = round(random.uniform(0, 100), 7)
        variation['liquids_production_kbd'] = round(random.uniform(0, 5), 8)
        variation['water_production_kbd'] = round(random.uniform(0, 20), 8)
        
        # Keep some fields the same for realism
        variation['data_source'] = base_record.get('data_source', 'Brazil - Agência Nacional do Petróleo (ANP)')
        variation['partition_0'] = 'latest'
        
        variations.append(variation)
    
    return variations


def create_duplicates(unique_records: list, duplicate_count: int) -> list:
    """Create duplicates by randomly selecting from unique records."""
    duplicates = []
    
    for _ in range(duplicate_count):
        # Randomly select a record to duplicate
        original = random.choice(unique_records)
        duplicate = copy.deepcopy(original)
        duplicates.append(duplicate)
    
    return duplicates


def main():
    """Main execution function."""
    # File paths
    input_file = Path("../external/mocked_response.json")
    output_file = Path("../external/mocked_response_duplicates.json")
    
    # Target counts
    target_total = 10000
    target_unique = 5000
    target_duplicates = 5000
    
    print("="*60)
    print("CREATING JSON FILE WITH DUPLICATES")
    print("="*60)
    print(f"Target total records: {target_total:,}")
    print(f"Target unique records: {target_unique:,}")
    print(f"Target duplicate records: {target_duplicates:,}")
    print()
    
    # Load original data
    original_data = load_original_data(input_file)
    original_records = original_data.get('value', [])
    
    if not original_records:
        print("Error: No records found in original data!")
        sys.exit(1)
    
    # Generate unique records based on original data
    print(f"Generating {target_unique:,} unique records...")
    unique_records = []
    
    # Use each original record as a template to generate variations
    records_per_template = target_unique // len(original_records)
    remaining_records = target_unique % len(original_records)
    
    for i, original_record in enumerate(original_records):
        # Generate variations for this template
        variations_count = records_per_template
        if i < remaining_records:
            variations_count += 1
        
        variations = generate_variations(original_record, variations_count)
        unique_records.extend(variations)
    
    print(f"✓ Generated {len(unique_records):,} unique records")
    
    # Create duplicates
    print(f"Creating {target_duplicates:,} duplicate records...")
    duplicate_records = create_duplicates(unique_records, target_duplicates)
    print(f"✓ Created {len(duplicate_records):,} duplicate records")
    
    # Combine and shuffle
    all_records = unique_records + duplicate_records
    random.shuffle(all_records)
    
    print(f"✓ Total records created: {len(all_records):,}")
    
    # Create output data structure
    output_data = copy.deepcopy(original_data)
    output_data['value'] = all_records
    
    # Save to file
    print(f"Saving data to {output_file}...")
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(output_data, f, indent=2, ensure_ascii=False)
    
    # Calculate file size
    file_size_mb = output_file.stat().st_size / (1024 * 1024)
    
    # Final summary
    print("\n" + "="*60)
    print("FILE CREATION COMPLETE!")
    print("="*60)
    print(f"Input file: {input_file}")
    print(f"Output file: {output_file}")
    print(f"File size: {file_size_mb:.2f} MB")
    print(f"Total records: {len(all_records):,}")
    print(f"Expected unique after dedup: {len(unique_records):,}")
    print(f"Expected duplicates removed: {len(duplicate_records):,}")
    print(f"Expected reduction: {(len(duplicate_records)/len(all_records))*100:.1f}%")
    print("="*60)
    
    # Verification
    print("\nVerification:")
    print(f"✓ Unique records generated: {len(unique_records):,}")
    print(f"✓ Duplicate records created: {len(duplicate_records):,}")
    print(f"✓ Total records: {len(all_records):,}")
    print(f"✓ Target achieved: {len(all_records) == target_total}")


if __name__ == "__main__":
    main()
